#+TITLE: Yippy

Yippy is a scripting language in development that is similar to LISP. It's my hobby project, and it's quite interesting since I'm learning a lot of new stuff and how things function behind the scenes.

But why have a language? Isn't it something everyone does when they're bored? Actually, I have some plans for the same, and I hope to get there soon.

* Features
- Variables (Can be declared using =let= keyword)
- Lambda Functions (Can be declared using =lambda= keyword)
- Arithmetic Operaions (=+,-,* and /=)
- Unary Operators (=+ and -= are supported. Will add =%,!,~ and &=)
- Bitwise Operators (Will added soon)
- Garbage Collector or a VM (Yet to decide)
- A standard library (Yet to implement)
- Compile to WASM (Yet to implement)
- Generate WASM (Yet to implement)
  
* Building
Right now, as of v0.0.1, only =gcc= and =make= is needed to compile this small language on Unix systems (Mac OS and Linux are briefly tested).

Currently, windows is supported (but also look [[https://github.com/basicfunc/yippy/issues/7][here]]) and you need =mingw= toolchain and =make= to compile.

If you face any issue on any operating system, please consider opening an issue or PR.

#+BEGIN_SRC shell
  # Clone this repo or Download locally from Release tags.
  git clone https://github.com/basicfunc/yippy.git
  make
#+END_SRC

* Contributing

* Thanksgiving 🙌
This project is heavily inspired by [[https://buildyourownlisp.com/][Build Your Own Lisp]] Book and uses [[https://github.com/orangeduck/mpc][mpc]] to parse the user input.
I really appreciate [[https://github.com/orangeduck][Daniel Holden]]'s work.
This project also uses [[https://github.com/antirez/linenoise][linenoise]] for command line interface written by [[https://github.com/antirez/][Salvatore Sanfilippo]]

* License
Yippy is licensed under the MIT License. See [[https://github.com/basicfunc/yippy/blob/main/LICENSE][LICENSE]] for more details.
