#+TITLE: Yippy

Yippy is a scripting language in development that is similar to LISP. It's my hobby project, and it's quite interesting since I'm learning a lot of new stuff and how things function behind the scenes.

But why have a language? Isn't it something everyone does when they're bored? Actually, I have some plans for the same, and I hope to get there soon.

* Features
- Variables (Can be declared using =let= keyword)
- Lambda Functions (Can be declared using =lambda= keyword)
- Arithmetic Operators (=+, -, *, / and %= are implemented)
- Relational Operators (~<,>,<=,=>,==,!=~ are implemented)
- Bitwise Operators (=&, |, ^, << and >>= are implemented)
- Logical Operators (=&& and ||=, are implemented)   
- Unary Operators (=+, -, ! and ~= are implemented)
- Directly evaluate a file (using ~-f or --file~ flag or using ~load~ function directly in file or cmdline)
- A standard library (Can be found in =stdlib/=)
- Compile to WASM (Yet to implement)
  
* Building
*NOTE*:- If you face any issue on any operating system, please consider opening an issue or PR.

*Dependencies* = =cmake gcc/clang=

#+BEGIN_SRC shell
  # Clone this repo or Download locally from Release tags.
  git clone https://github.com/basicfunc/yippy.git
  cmake --build .
#+END_SRC

* Contributing
- Pick an issue, or create an new issue. Provide adequate documentation for the issue.
- Assign the issue or get it assigned.
- Work on the code, once finished, raise a pull request.
- =Yippy= is written in pure C, hence take care of pointers.
- If you've any idea regarding this language, you can open a issue to discuss it.
- Current development branch for this project is =main= branch.

* Thanksgiving 🙌
This project is heavily inspired by [[https://buildyourownlisp.com/][Build Your Own Lisp]] Book and uses [[https://github.com/orangeduck/mpc][mpc]] to parse the user input.
I really appreciate [[https://github.com/orangeduck][Daniel Holden]]'s work.
This project also uses [[https://github.com/antirez/linenoise][linenoise]] for command line interface written by [[https://github.com/antirez/][Salvatore Sanfilippo]].

* License
Yippy is licensed under the MIT License. See [[https://github.com/basicfunc/yippy/blob/main/LICENSE][LICENSE]] for more details.
