#!/bin/env bash

set -e

export YIPPY_EXE=${YIPPY_DIR}/yippy

if_ok() {
	if [[ $1 -eq $2 ]]; then
		echo -e "Test:OK\n"
	else
		echo -e "Test:Failed\n"
		exit 1
	fi

}

export -f if_ok

echo "*************TEST****************"

for file in *.sh; do
	./${file}
done
